# Generated by Django 4.0.3 on 2022-03-31 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyuseranswer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='survey.surveyquestion', verbose_name='pergunta'),
            preserve_default=False,
        ),
    ]
