# Generated by Django 4.0.3 on 2022-03-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_surveyuseranswer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
